modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "glassbreaker"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''
${description}
'''
#logoFile = ""

[[dependencies.glassbreaker]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glassbreaker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
