modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "glassbreaker"
version = "${version}"
displayName = "${name}"
displayURL = "${sources}"
authors = "${author}"
description = '''
${description}
'''
logoFile = "icon.png"

[[dependencies.glassbreaker]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glassbreaker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
